/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testswim;

import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author Dushan
 */
public class SwimmingGUI extends javax.swing.JFrame {

    private final ArrayList<Person> allpeople;
    private int playerCount;
    private int watchersCount;
    private int judgersCount;
    private int staffCount;
    private Swimmer swimmer1;
    private Swimmer swimmer2;
    private Swimmer swimmer3;
    private Swimmer swimmer4;
    private Swimmer swimmer5;
    Vistle vistle;
    private int winningCount;
    public ScoreBoard scoreBoard;

    /**
     * Creates new form SwimmingGUI
     */
    public SwimmingGUI(ArrayList<Person> allpeople, ScoreBoard scoreBoard) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(3);
        this.allpeople = allpeople;
        this.addPeopleToLabels();

        this.swimmerIconHide();
        this.judgeIconHide();
        this.supportingStaffIconHide();
        this.spectatorIconHide();

        this.setVisible(true);

        this.scoreBoard = scoreBoard;
        scoreBoard.swimmingGui = this;

        this.vistle = scoreBoard.vistle;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        spectatorLabel1 = new javax.swing.JLabel();
        spectatorLabel2 = new javax.swing.JLabel();
        spectatorLabel3 = new javax.swing.JLabel();
        spectatorLabel4 = new javax.swing.JLabel();
        spectatorLabel5 = new javax.swing.JLabel();
        spectatorLabel6 = new javax.swing.JLabel();
        spectatorLabel7 = new javax.swing.JLabel();
        spectatorLabel8 = new javax.swing.JLabel();
        spectatorLabel9 = new javax.swing.JLabel();
        spectatorLabel10 = new javax.swing.JLabel();
        spectatorLabel11 = new javax.swing.JLabel();
        spectatorLabel12 = new javax.swing.JLabel();
        spectatorLabel13 = new javax.swing.JLabel();
        spectatorLabel14 = new javax.swing.JLabel();
        spectatorLabel15 = new javax.swing.JLabel();
        spectatorLabel16 = new javax.swing.JLabel();
        spectatorLabel17 = new javax.swing.JLabel();
        spectatorLabel18 = new javax.swing.JLabel();
        spectatorLabel19 = new javax.swing.JLabel();
        spectatorLabel20 = new javax.swing.JLabel();
        ScoreBoardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreBoardTable = new javax.swing.JTable();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        start = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        swimming4 = new javax.swing.JLabel();
        swimming3 = new javax.swing.JLabel();
        swimming1 = new javax.swing.JLabel();
        swimming2 = new javax.swing.JLabel();
        swimming5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        swimReadyLabel2 = new javax.swing.JLabel();
        swimReadyLabel3 = new javax.swing.JLabel();
        swimReadyLabel1 = new javax.swing.JLabel();
        swimReadyLabel5 = new javax.swing.JLabel();
        swimReadyLabel4 = new javax.swing.JLabel();
        MainJudgeLabel = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        judgeLabel2 = new javax.swing.JLabel();
        judgeLabel1 = new javax.swing.JLabel();
        judgeLabel3 = new javax.swing.JLabel();
        judgeLabel4 = new javax.swing.JLabel();
        judgeLabel5 = new javax.swing.JLabel();
        supportingStaffLabel1 = new javax.swing.JLabel();
        supportingStaffLabel2 = new javax.swing.JLabel();
        supportingStaffLabel3 = new javax.swing.JLabel();
        supportingStaffLabel4 = new javax.swing.JLabel();
        supportingStaffLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));
        jPanel1.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setMinimumSize(new java.awt.Dimension(899, 182));
        jPanel2.setName(""); // NOI18N

        spectatorLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyBlue.png"))); // NOI18N

        spectatorLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyBlue.png"))); // NOI18N

        spectatorLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyBlue.png"))); // NOI18N

        spectatorLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyBlue.png"))); // NOI18N

        spectatorLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyBlue.png"))); // NOI18N

        spectatorLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyBlue.png"))); // NOI18N

        spectatorLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyBlue.png"))); // NOI18N

        spectatorLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyBlue.png"))); // NOI18N

        spectatorLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        spectatorLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyBlue.png"))); // NOI18N

        spectatorLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/girlRed.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spectatorLabel1)
                    .addComponent(spectatorLabel2))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spectatorLabel6)
                    .addComponent(spectatorLabel12))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(spectatorLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(spectatorLabel9)))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spectatorLabel5)
                    .addComponent(spectatorLabel10))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spectatorLabel3)
                    .addComponent(spectatorLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(spectatorLabel4)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(spectatorLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spectatorLabel14)
                    .addComponent(spectatorLabel13))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spectatorLabel15)
                    .addComponent(spectatorLabel16))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(spectatorLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(spectatorLabel20))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(spectatorLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(spectatorLabel19)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spectatorLabel20)
                    .addComponent(spectatorLabel11)
                    .addComponent(spectatorLabel3)
                    .addComponent(spectatorLabel2)
                    .addComponent(spectatorLabel6)
                    .addComponent(spectatorLabel5)
                    .addComponent(spectatorLabel9)
                    .addComponent(spectatorLabel13)
                    .addComponent(spectatorLabel16)
                    .addComponent(spectatorLabel18))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spectatorLabel4)
                    .addComponent(spectatorLabel1)
                    .addComponent(spectatorLabel8)
                    .addComponent(spectatorLabel7)
                    .addComponent(spectatorLabel10)
                    .addComponent(spectatorLabel12)
                    .addComponent(spectatorLabel14)
                    .addComponent(spectatorLabel17)
                    .addComponent(spectatorLabel15)
                    .addComponent(spectatorLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ScoreBoardPanel.setBackground(new java.awt.Color(204, 204, 255));
        ScoreBoardPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        jLabel1.setText("Score board");

        scoreBoardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", null, null, null},
                {"2", null, null, null},
                {"3", null, null, null},
                {"4", null, null, null},
                {"5", null, null, null}
            },
            new String [] {
                "Lane", "Name", "Time", "Position"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scoreBoardTable.setRowHeight(35);
        jScrollPane1.setViewportView(scoreBoardTable);
        if (scoreBoardTable.getColumnModel().getColumnCount() > 0) {
            scoreBoardTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            scoreBoardTable.getColumnModel().getColumn(0).setMaxWidth(40);
            scoreBoardTable.getColumnModel().getColumn(2).setPreferredWidth(125);
            scoreBoardTable.getColumnModel().getColumn(3).setPreferredWidth(60);
        }

        javax.swing.GroupLayout ScoreBoardPanelLayout = new javax.swing.GroupLayout(ScoreBoardPanel);
        ScoreBoardPanel.setLayout(ScoreBoardPanelLayout);
        ScoreBoardPanelLayout.setHorizontalGroup(
            ScoreBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ScoreBoardPanelLayout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(76, 76, 76))
        );
        ScoreBoardPanelLayout.setVerticalGroup(
            ScoreBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScoreBoardPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        start.setText("Start");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(102, 102, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel9.setMaximumSize(new java.awt.Dimension(757, 32767));
        jPanel9.setPreferredSize(new java.awt.Dimension(757, 342));

        swimming4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimmingBlue.png"))); // NOI18N

        swimming3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimmingBlue.png"))); // NOI18N

        swimming1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimmingBlue.png"))); // NOI18N

        swimming2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimmingBlue.png"))); // NOI18N

        swimming5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimmingBlue.png"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(swimming4)
                    .addComponent(swimming3)
                    .addComponent(swimming2)
                    .addComponent(swimming5)
                    .addComponent(swimming1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 664, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(swimming1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(swimming2)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(swimming3)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(swimming4)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(swimming5)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        swimReadyLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimReadyBlue.png"))); // NOI18N

        swimReadyLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimReadyBlue.png"))); // NOI18N

        swimReadyLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimReadyBlue.png"))); // NOI18N

        swimReadyLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimReadyBlue.png"))); // NOI18N

        swimReadyLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/swimReadyBlue.png"))); // NOI18N

        MainJudgeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/judge.png"))); // NOI18N

        judgeLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyGreen.png"))); // NOI18N

        judgeLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyGreen.png"))); // NOI18N

        judgeLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyGreen.png"))); // NOI18N

        judgeLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyGreen.png"))); // NOI18N

        judgeLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/boyGreen.png"))); // NOI18N

        supportingStaffLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/staffRight.png"))); // NOI18N

        supportingStaffLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/staffRight.png"))); // NOI18N

        supportingStaffLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/staffRight.png"))); // NOI18N

        supportingStaffLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/staffRight.png"))); // NOI18N

        supportingStaffLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/testswim/staffRight.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(supportingStaffLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(supportingStaffLabel4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(supportingStaffLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(MainJudgeLabel)
                                        .addGap(40, 40, 40)
                                        .addComponent(supportingStaffLabel5))
                                    .addComponent(supportingStaffLabel1)))))
                    .addComponent(ScoreBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filler2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(swimReadyLabel1)
                                    .addGap(20, 20, 20))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(swimReadyLabel5)
                                        .addComponent(swimReadyLabel4)
                                        .addComponent(swimReadyLabel3))
                                    .addGap(18, 18, 18)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(swimReadyLabel2)
                                .addGap(18, 18, 18)))
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(judgeLabel1)
                                    .addComponent(judgeLabel2)
                                    .addComponent(judgeLabel4)
                                    .addComponent(judgeLabel3)
                                    .addComponent(judgeLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ScoreBoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MainJudgeLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(supportingStaffLabel5)
                                            .addComponent(supportingStaffLabel3))
                                        .addGap(35, 35, 35)
                                        .addComponent(supportingStaffLabel4)
                                        .addGap(45, 45, 45)
                                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 618, Short.MAX_VALUE)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(swimReadyLabel3)
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(supportingStaffLabel1)
                                        .addGap(22, 22, 22)
                                        .addComponent(supportingStaffLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(swimReadyLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(swimReadyLabel5))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(48, 48, 48)
                                                .addComponent(judgeLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(judgeLabel2))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(swimReadyLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(swimReadyLabel2)))
                                        .addGap(38, 38, 38)
                                        .addComponent(judgeLabel3)
                                        .addGap(38, 38, 38)
                                        .addComponent(judgeLabel4)
                                        .addGap(38, 38, 38)
                                        .addComponent(judgeLabel5))
                                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        // TODO add your handling code here:
        vistle.blow();
        Random sleep = new Random();
        if (swimmer1 != null) {
            //            swimmer1.setJPanelAddress(swimming1);
            swimmer1.runLabel(swimming1, swimmer1.sleep);
            swimReadyLabel1.hide();
            swimming1.setVisible(true);
            //            runPlayer1Label();
        }
        if (swimmer2 != null) {
            //            swimmer1.setJPanelAddress(swimming2);
            swimmer2.runLabel(swimming2, swimmer2.sleep);
            swimReadyLabel2.hide();
            swimming2.setVisible(true);
            //            runPlayer2Label();
        }
        if (swimmer3 != null) {
            //            swimmer1.setJPanelAddress(swimming3);
            swimmer3.runLabel(swimming3, swimmer3.sleep);
            swimReadyLabel3.hide();
            swimming3.setVisible(true);
            //            runPlayer3Label();
        }
        if (swimmer4 != null) {
            //            swimmer1.setJPanelAddress(swimming4);
            swimmer4.runLabel(swimming4, swimmer4.sleep);
            swimReadyLabel4.hide();
            swimming4.setVisible(true);
            //            runPlayer4Label();
        }
        if (swimmer5 != null) {
            //            swimmer1.setJPanelAddress(swimming5);
            swimmer5.runLabel(swimming5, swimmer5.sleep);
            swimReadyLabel5.hide();
            swimming5.setVisible(true);
            //            runPlayer5Label();
        }
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SwimmingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SwimmingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SwimmingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SwimmingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new SwimmingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainJudgeLabel;
    private javax.swing.JPanel ScoreBoardPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judgeLabel1;
    private javax.swing.JLabel judgeLabel2;
    private javax.swing.JLabel judgeLabel3;
    private javax.swing.JLabel judgeLabel4;
    private javax.swing.JLabel judgeLabel5;
    private javax.swing.JTable scoreBoardTable;
    private javax.swing.JLabel spectatorLabel1;
    private javax.swing.JLabel spectatorLabel10;
    private javax.swing.JLabel spectatorLabel11;
    private javax.swing.JLabel spectatorLabel12;
    private javax.swing.JLabel spectatorLabel13;
    private javax.swing.JLabel spectatorLabel14;
    private javax.swing.JLabel spectatorLabel15;
    private javax.swing.JLabel spectatorLabel16;
    private javax.swing.JLabel spectatorLabel17;
    private javax.swing.JLabel spectatorLabel18;
    private javax.swing.JLabel spectatorLabel19;
    private javax.swing.JLabel spectatorLabel2;
    private javax.swing.JLabel spectatorLabel20;
    private javax.swing.JLabel spectatorLabel3;
    private javax.swing.JLabel spectatorLabel4;
    private javax.swing.JLabel spectatorLabel5;
    private javax.swing.JLabel spectatorLabel6;
    private javax.swing.JLabel spectatorLabel7;
    private javax.swing.JLabel spectatorLabel8;
    private javax.swing.JLabel spectatorLabel9;
    private javax.swing.JButton start;
    private javax.swing.JLabel supportingStaffLabel1;
    private javax.swing.JLabel supportingStaffLabel2;
    private javax.swing.JLabel supportingStaffLabel3;
    private javax.swing.JLabel supportingStaffLabel4;
    private javax.swing.JLabel supportingStaffLabel5;
    private javax.swing.JLabel swimReadyLabel1;
    private javax.swing.JLabel swimReadyLabel2;
    private javax.swing.JLabel swimReadyLabel3;
    private javax.swing.JLabel swimReadyLabel4;
    private javax.swing.JLabel swimReadyLabel5;
    private javax.swing.JLabel swimming1;
    private javax.swing.JLabel swimming2;
    private javax.swing.JLabel swimming3;
    private javax.swing.JLabel swimming4;
    private javax.swing.JLabel swimming5;
    // End of variables declaration//GEN-END:variables

    public void addPeopleToLabels() {
        for (Person person : allpeople) {
            try {
                Swimmer swimmer = (Swimmer) person;
                swimmer.setGuiAddress(this);
                playerCount++;
                if (playerCount == 1) {
                    swimmer1 = swimmer;
                    swimReadyLabel1.setVisible(true);
                    scoreBoardTable.getModel().setValueAt(swimmer.getName(), 0, 1);
                } else if (playerCount == 2) {
                    swimmer2 = swimmer;
                    swimReadyLabel2.setVisible(true);
                    scoreBoardTable.getModel().setValueAt(swimmer.getName(), 1, 1);
                } else if (playerCount == 3) {
                    swimmer3 = swimmer;
                    swimReadyLabel3.setVisible(true);
                    scoreBoardTable.getModel().setValueAt(swimmer3.getName(), 2, 1);
                } else if (playerCount == 4) {
                    swimmer4 = swimmer;
                    swimReadyLabel4.setVisible(true);
                    scoreBoardTable.getModel().setValueAt(swimmer4.getName(), 3, 1);
                } else if (playerCount == 5) {
                    swimmer5 = swimmer;
                    swimReadyLabel5.setVisible(true);
                    scoreBoardTable.getModel().setValueAt(swimmer5.getName(), 4, 1);
                }
            } catch (ClassCastException notSwimmer) {

                try {
                    Judge judge = (Judge) person;
                    judgersCount++;
                    if (judgersCount == 1) {
                        MainJudgeLabel.setVisible(true);
                    } else if (judgersCount == 2) {
                        judgeLabel1.setVisible(true);
                    } else if (playerCount == 3) {
                        judgeLabel2.setVisible(true);
                    } else if (playerCount == 4) {
                        judgeLabel3.setVisible(true);
                    } else if (playerCount == 5) {
                        judgeLabel4.setVisible(true);
                    }

                } catch (ClassCastException notJudge) {

                    try {
                        SupportingStaff supportingStaff = (SupportingStaff) person;
                        staffCount++;
                        if (staffCount == 1) {
                            supportingStaffLabel1.setVisible(true);
                        } else if (staffCount == 2) {
                            supportingStaffLabel2.setVisible(true);
                        } else if (staffCount == 3) {
                            supportingStaffLabel3.setVisible(true);
                        } else if (staffCount == 4) {
                            supportingStaffLabel4.setVisible(true);
                        } else if (staffCount == 5) {
                            supportingStaffLabel5.setVisible(true);
                        }

                    } catch (ClassCastException notSupportingStaff) {

                        try {
                            Spectator spectator = (Spectator) person;
                            watchersCount++;
                            if (watchersCount == 1) {
                                spectatorLabel1.setVisible(true);
                            } else if (watchersCount == 2) {
                                spectatorLabel2.setVisible(true);
                            } else if (watchersCount == 3) {
                                spectatorLabel3.setVisible(true);
                            } else if (watchersCount == 4) {
                                spectatorLabel4.setVisible(true);
                            } else if (watchersCount == 5) {
                                spectatorLabel5.setVisible(true);
                            } else if (watchersCount == 6) {
                                spectatorLabel6.setVisible(true);
                            } else if (watchersCount == 7) {
                                spectatorLabel7.setVisible(true);
                            } else if (watchersCount == 8) {
                                spectatorLabel8.setVisible(true);
                            } else if (watchersCount == 9) {
                                spectatorLabel9.setVisible(true);
                            } else if (watchersCount == 10) {
                                spectatorLabel10.setVisible(true);
                            } else if (watchersCount == 11) {
                                spectatorLabel11.setVisible(true);
                            } else if (watchersCount == 12) {
                                spectatorLabel12.setVisible(true);
                            } else if (watchersCount == 13) {
                                spectatorLabel13.setVisible(true);
                            } else if (watchersCount == 14) {
                                spectatorLabel14.setVisible(true);
                            } else if (watchersCount == 15) {
                                spectatorLabel15.setVisible(true);
                            } else if (watchersCount == 16) {
                                spectatorLabel16.setVisible(true);
                            } else if (watchersCount == 17) {
                                spectatorLabel17.setVisible(true);
                            } else if (watchersCount == 18) {
                                spectatorLabel18.setVisible(true);
                            } else if (watchersCount == 19) {
                                spectatorLabel19.setVisible(true);
                            } else if (watchersCount == 20) {
                                spectatorLabel20.setVisible(true);
                            }
                            

                        } catch (ClassCastException notSpectator) {
                            System.out.println("there is error:" + notSpectator);
                        }
                    }

                }
            }

        }
    }

    private void swimmerIconHide() {
        
        swimReadyLabel1.setVisible(false);
        swimReadyLabel2.setVisible(false);
        swimReadyLabel3.setVisible(false);
        swimReadyLabel4.setVisible(false);
        swimReadyLabel5.setVisible(false);

        swimming1.setVisible(false);
        swimming2.setVisible(false);
        swimming3.setVisible(false);
        swimming4.setVisible(false);
        swimming5.setVisible(false);
    }

    private void judgeIconHide() {
        MainJudgeLabel.setVisible(false);
        judgeLabel1.setVisible(false);
        judgeLabel2.setVisible(false);
        judgeLabel3.setVisible(false);
        judgeLabel4.setVisible(false);
        judgeLabel5.setVisible(false);
    }

    private void supportingStaffIconHide() {
        supportingStaffLabel1.setVisible(false);
        supportingStaffLabel2.setVisible(false);
        supportingStaffLabel3.setVisible(false);
        supportingStaffLabel4.setVisible(false);
        supportingStaffLabel5.setVisible(false);

    }

    private void spectatorIconHide() {
        spectatorLabel1.setVisible(false);
        spectatorLabel2.setVisible(false);
        spectatorLabel3.setVisible(false);
        spectatorLabel4.setVisible(false);
        spectatorLabel5.setVisible(false);

        spectatorLabel6.setVisible(false);
        spectatorLabel7.setVisible(false);
        spectatorLabel8.setVisible(false);
        spectatorLabel9.setVisible(false);
        spectatorLabel10.setVisible(false);

        spectatorLabel11.setVisible(false);
        spectatorLabel12.setVisible(false);
        spectatorLabel13.setVisible(false);
        spectatorLabel14.setVisible(false);
        spectatorLabel15.setVisible(false);

        spectatorLabel16.setVisible(false);
        spectatorLabel17.setVisible(false);
        spectatorLabel18.setVisible(false);
        spectatorLabel19.setVisible(false);
        spectatorLabel20.setVisible(false);

    }

    public void displayScoreSwimmer1(String time, String position) {
        scoreBoardTable.getModel().setValueAt(time, 0, 2);
        scoreBoardTable.getModel().setValueAt(position + "", 0, 3);

    }

    public void displayScoreSwimmer2(String time, String position) {
        scoreBoardTable.getModel().setValueAt(time, 1, 2);
        scoreBoardTable.getModel().setValueAt(position + "", 1, 3);
    }

    public void displayScoreSwimmer3(String time, String position) {
        scoreBoardTable.getModel().setValueAt(time, 2, 2);
        scoreBoardTable.getModel().setValueAt(position + "", 2, 3);
    }

    public void displayScoreSwimmer4(String time, String position) {
        scoreBoardTable.getModel().setValueAt(time, 3, 2);
        scoreBoardTable.getModel().setValueAt(position + "", 3, 3);
    }

    public void displayScoreSwimmer5(String time, String position) {
        scoreBoardTable.getModel().setValueAt(time, 4, 2);
        scoreBoardTable.getModel().setValueAt(position + "", 4, 3);
    }

}
